version: "3.5"
services:
  identityDb:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - identityDb:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'identity'
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      
  rabbit:
    image: rabbitmq:management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./docker/rabbit/data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'user'
      RABBITMQ_DEFAULT_PASS: 'password'

volumes:
  identityDb:
    driver: local
