{{- range $certificate := .Values.certificates }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $certificate.name }}
spec:
  secretName: "{{ $certificate.name }}-tls"
  renewBefore: 240h
  {{ if $certificate.dnsNames }}
  dnsNames:
    {{- range $certificate.dnsNames }}
    - {{ . | quote }}
    {{- end }}
  {{ end }}
  {{ if $certificate.isCA }}
  isCA: {{ $certificate.isCA }}
  {{ end }}
  {{ if $certificate.commonName }}
  commonName: {{ $certificate.commonName }}
  {{ end }}
  issuerRef:
    name: {{ $certificate.issuerRef.name }}
    kind: {{ $certificate.issuerRef.kind }}
{{- end }}

