apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-aggregator-cm
data:
  fluentd.conf: |
    # Ignore fluentd own events
    <match fluent.**>
      @type null
    </match>
    
    @include fluentd-inputs.conf
    @include fluentd-output.conf
  fluentd-inputs.conf: |
    # TCP input to receive logs from
    <source>
      @type forward
      bind 0.0.0.0
      port 24224
    </source>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      bind 0.0.0.0
      port 9880
    </source>

  fluentd-output.conf: |
    # Throw the healthcheck to the standard output
    <match fluentd.healthcheck>
      @type null
    </match>
    
    # Send the logs to the standard output
    <match kubernetes.var.log.containers.**app**.log>
      @type elasticsearch
      include_tag_key true
      hosts "#{ENV['ELASTICSEARCH_HOST']}"
      port "#{ENV['ELASTICSEARCH_PORT']}"
      user "#{ENV['ELASTICSEARCH_USERNAME']}"
      password "#{ENV['ELASTICSEARCH_PASSWORD']}"
      scheme https
      ssl_verify false
      ssl_version TLSv1_2
      index_name "app-logs"

      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match>

    <match linkerd-proxy.var.log.containers.**.log>
      @type copy
      <store>
        @type elasticsearch
        include_tag_key true
        hosts "#{ENV['ELASTICSEARCH_HOST']}"
        port "#{ENV['ELASTICSEARCH_PORT']}"
        user "#{ENV['ELASTICSEARCH_USERNAME']}"
        password "#{ENV['ELASTICSEARCH_PASSWORD']}"
        scheme https
        ssl_verify false
        ssl_version TLSv1_2
        index_name "linkerd-proxy"

        <buffer>
          @type file
          path /opt/bitnami/fluentd/logs/buffers/logs-linkerd-proxy.buffer
          flush_thread_count 2
          flush_interval 5s
        </buffer>
      </store>
      <store>
        @type stdout
      </store>
    </match>
