{{- range $deployment := .Values.deployments }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ $deployment.name }}-deployment"
  labels:
    app: "{{ $deployment.name }}-deployment"
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: "{{ $deployment.name }}-app"
  template:
    metadata:
      name: "{{ $deployment.name }}-pod"
      annotations:
        prometheus.io/scrape: "true"
        linkerd.io/inject: enabled

        {{ if $deployment.metricsPort }}
        prometheus.io/port: "{{ $deployment.metricsPort }}"
        {{ else }}
        prometheus.io/port: "{{ $deployment.containerPort }}"
        {{ end }}

        {{ if $deployment.linkerdDebug }}
        config.linkerd.io/enable-debug-sidecar: "true"
        {{ end }}
      labels:
        app: "{{ $deployment.name }}-app"
    spec:
      containers:
        - name: "{{ $deployment.name }}-app"
          image: {{ $deployment.image }}

          {{ if $deployment.command }}
          command: {{ $deployment.command }}
          {{ end }}

          {{ if $deployment.args }}
          args: {{ $deployment.args }}
          {{ end }}

          {{ if $deployment.imagePullPolicy }}
          imagePullPolicy: {{ $deployment.imagePullPolicy }}
          {{ end }}

          {{ range $port := $deployment.ports }}
          ports:
            - containerPort: {{ $port.containerPort }}
          {{ end }}
          env:
            {{ if $deployment.env }}
            {{- range $key, $value := $deployment.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{ end }}
          
          {{ if $deployment.envFrom }}
          envFrom:
          {{ toYaml $deployment.envFrom | nindent 10 }}
          {{ end }}
{{- end -}}
