{{- range $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  {{ if $secret.namespace }}
  namespace: {{ $secret.namespace }}
  {{ end }}
type: {{ $secret.type }}
data:
  {{ range $property := $secret.data }}
  {{ $property.name }}: |-
    {{ $.Files.Get $property.file | b64enc }}
  {{ end }}
{{- end }}
