name: Banking ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unitTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --no-restore

  buildAndPushGatewayRoot:
    runs-on: ubuntu-latest
    needs:
      - unitTests
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Gateway.Root/Dockerfile
          push: true
          tags: vladerlord/vladerlord.banking.gateway.root:latest

  buildAndPushServiceBankAccount:
    runs-on: ubuntu-latest
    needs:
      - unitTests
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Service.BankAccount/Dockerfile
          push: true
          tags: vladerlord/vladerlord.banking.service.bankaccount:latest

  buildAndPushServiceCurrency:
    runs-on: ubuntu-latest
    needs:
      - unitTests
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Service.Currency/Dockerfile
          push: true
          tags: vladerlord/vladerlord.banking.service.currency:latest
  
  buildAndPushServiceIdentity:
    runs-on: ubuntu-latest
    needs:
      - unitTests
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Service.Identity/Dockerfile
          push: true
          tags: vladerlord/vladerlord.banking.service.identity:latest
  
  buildAndPushServiceIdentityNotifier:
    runs-on: ubuntu-latest
    needs:
      - unitTests
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Service.IdentityNotifier/Dockerfile
          push: true
          tags: vladerlord/vladerlord.banking.service.identitynotifier:latest

  buildAndPushServicePersonalData:
    runs-on: ubuntu-latest
    needs:
      - unitTests
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Service.PersonalData/Dockerfile
          push: true
          tags: vladerlord/vladerlord.banking.service.personaldata:latest
